Traceback (most recent call last):
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/swissel/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/swissel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random

minNumber = 1
maxNumber = 10

#  Get a random number between 1 and 10
randomNumber = random.randint(minNumber, maxNumber)

userGuess = -1

while(userGuess != randomNumber):
    userPrompt = "Guess a number between " + str(minNumber) + " and " + str(maxNumber) + ": "
    
    userGuess = input(userPrompt)      #  Prompt the user
    
    userGuess = int(userGuess)

print("You have guessed the correct number! " + str(userGuess))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m<ipython-input-17-2231bbc0409e>[0m in [0;36m<module>[0;34m[0m
[1;32m     12[0m     [0muserPrompt[0m [0;34m=[0m [0;34m"Guess a number between "[0m [0;34m+[0m [0mstr[0m[0;34m([0m[0mminNumber[0m[0;34m)[0m [0;34m+[0m [0;34m" and "[0m [0;34m+[0m [0mstr[0m[0;34m([0m[0mmaxNumber[0m[0;34m)[0m [0;34m+[0m [0;34m": "[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0;34m[0m[0m
[0;32m---> 14[0;31m     [0muserGuess[0m [0;34m=[0m [0minput[0m[0;34m([0m[0muserPrompt[0m[0;34m)[0m      [0;31m#  Prompt the user[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     15[0m [0;34m[0m[0m
[1;32m     16[0m     [0muserGuess[0m [0;34m=[0m [0mint[0m[0;34m([0m[0muserGuess[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m    844[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    845[0m             raise StdinNotImplementedError(
[0;32m--> 846[0;31m                 [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    847[0m             )
[1;32m    848[0m         return self._input_request(str(prompt),

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

